### ISSUE TITLE
Crash w/ Improving Minecraft Mod

### ISSUE THREAD

**Issue by WenXin20** [AtomicBlom/ShearMadness#25]
I got this crash while generating new chunks with the[ Improving Minecraft Mod](https://minecraft.curseforge.com/projects/improving-minecraft). Forge 2075
[Crash Report](http://pastebin.com/VvZCNK4d)

**Comment by AtomicBlom** [comment]
Thanks very much for the report.
It seems to be related to Wild Sheep.

I'll try get a fix published for this on my lunch break today.

Bug fix notes:
Quick investigation reveals that Capabilities are attached to sheep by checking that a sheep is exactly of the type EntitySheep.
AI is later added to sheep based on if it extends sheep.

Fix will be to add AI based on if it has the ChiseledSheep capability rather than the type of the sheep.

**Comment by WenXin20** [comment]
Thanks

**Comment by AtomicBlom** [comment]
Hi @WenXin20, I'm still at work so I can't test this, but there's a preliminary version that should fix your issue
https://github.com/AtomicBlom/ShearMadness/releases/tag/1.1.2

I'll test it tonight when I can

**Comment by WenXin20** [comment]
That version seems to crash on forge 2076 when creating a new world: [Crash Log](http://pastebin.com/hGuBDNYz)

**Comment by AtomicBlom** [comment]
I rewrote a lot of code that I sincerely hope might have solved this issue. I've been unable to reproduce the problem on my local machine. Check out 1.2.1 on CurseForge. (I stuffed up and haven't released it properly on github)

**Comment by WenXin20** [comment]
It works :)

**Comment by AtomicBlom** [comment]
Awesome, thanks for letting me know :D
